[package]
name = "t3-framed-wire"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-rs = { path = "../../../strata-rs/" }
tower-http = { version = "0.5", features = ["cors"] }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.18"
hex = "0.4.3"
bytes = "1.11.0"
